'use strict'
export const FETCH_TOPIC_REQUEST = 'FETCH_TOPIC_REQUEST'
export const FETCH_TOPIC_SUCCESS = 'FETCH_TOPIC_SUCCESS'
export const FETCH_TOPIC_FAILURE = 'FETCH_TOPIC_FAILURE'

export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST'
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS'
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE'

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'

export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST'
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS'
export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE'

export const FETCH_RELATED_ARTICLES_REQUEST = 'FETCH_RELATED_ARTICLES_REQUEST'
export const FETCH_RELATED_ARTICLES_SUCCESS = 'FETCH_RELATED_ARTICLES_SUCCESS'
export const FETCH_RELATED_ARTICLES_FAILURE = 'FETCH_RELATED_ARTICLES_FAILURE'

export const FETCH_ARTICLES_BY_GROUP_UUID_REQUEST = 'FETCH_ARTICLES_BY_GROUP_UUID_REQUEST'
export const FETCH_ARTICLES_BY_GROUP_UUID_SUCCESS = 'FETCH_ARTICLES_BY_GROUP_UUID_SUCCESS'
export const FETCH_ARTICLES_BY_GROUP_UUID_FAILURE = 'FETCH_ARTICLES_BY_GROUP_UUID_FAILURE'

export const FETCH_AUTHOR_DETAILS_REQUEST = 'FETCH_AUTHOR_DETAILS_REQUEST'
export const FETCH_AUTHOR_DETAILS_SUCCESS = 'FETCH_AUTHOR_DETAILS_SUCCESS'
export const FETCH_AUTHOR_DETAILS_FAILURE = 'FETCH_AUTHOR_DETAILS_FAILURE'

export const SEARCH_AUTHORS_REQUEST = 'SEARCH_AUTHORS_REQUEST'
export const SEARCH_AUTHORS_SUCCESS = 'SEARCH_AUTHORS_SUCCESS'
export const SEARCH_AUTHORS_FAILURE = 'SEARCH_AUTHORS_FAILURE'

export const LIST_ALL_AUTHORS_REQUEST = 'LIST_ALL_AUTHORS_REQUEST'
export const LIST_ALL_AUTHORS_SUCCESS = 'LIST_ALL_AUTHORS_SUCCESS'
export const LIST_ALL_AUTHORS_FAILURE = 'LIST_ALL_AUTHORS_FAILURE'

export const FETCH_AUTHOR_COLLECTION_REQUEST = 'FETCH_AUTHOR_COLLECTION_REQUEST'
export const FETCH_AUTHOR_COLLECTION_FAILURE = 'FETCH_AUTHOR_COLLECTION_FAILURE'
export const FETCH_AUTHOR_COLLECTION_SUCCESS = 'FETCH_AUTHOR_COLLECTION_SUCCESS'

export const FETCH_FEATURE_ARTICLES_REQUEST = 'FETCH_FEATURE_ARTICLES_REQUEST'
export const FETCH_FEATURE_ARTICLES_SUCCESS = 'FETCH_FEATURE_ARTICLES_SUCCESS'
export const FETCH_FEATURE_ARTICLES_FAILURE = 'FETCH_FEATURE_ARTICLES_FAILURE'

export const SET_ARTICLE_TOPIC_LIST = 'SET_ARTICLE_TOPIC_LIST'
export const SET_BOOKMARKS_OF_LONGFORM_ARTICLE = 'SET_BOOKMARKS_OF_LONGFORM_ARTICLE'
export const SET_HEADER_INFO = 'SET_HEADER_INFO'
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE'
export const SET_PAGE_THEME = 'SET_PAGE_THEME'
export const SET_PAGE_TYPE = 'SET_PAGE_TYPE'
export const SET_PROGRESS_PRECENTAGE = 'SET_PROGRESS_PRECENTAGE'

export const SET_ARTICLE_TOOLS = 'SET_ARTICLE_TOOLS'

export const SET_NEXT_POPUP_TIME_STAMP = 'SET_NEXT_POPUP_TIME_STAMP'

// actions on bookmarks
export const singleBookmark = {
  read: {
    request: 'request to fetch single bookmark',
    success: 'succes to fetch single bookmark',
    failure: 'fail to fetch single bookmark'
  },
  create: {
    request: 'request to  create single bookmark',
    success: 'succes to create single bookmark',
    failure: 'fail to create single bookmark'
  },
  delete: {
    request: 'request to  delete single bookmark',
    success: 'succes to delete single bookmark',
    failure: 'fail to delete single bookmark'
  }
}

export const multipleBookMarks = {
  read: {
    request: 'request to fetch multiple bookmarks',
    success: 'succes to fetch multiple bookmarks',
    failure: 'fail to fetch multiple bookmarks'
  }
}
