'use strict'
export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST'
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS'
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE'

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'

export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST'
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS'
export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE'

export const FETCH_RELATED_ARTICLES_REQUEST = 'FETCH_RELATED_ARTICLES_REQUEST'
export const FETCH_RELATED_ARTICLES_SUCCESS = 'FETCH_RELATED_ARTICLES_SUCCESS'
export const FETCH_RELATED_ARTICLES_FAILURE = 'FETCH_RELATED_ARTICLES_FAILURE'

export const FETCH_ARTICLES_BY_GROUP_UUID_REQUEST = 'FETCH_ARTICLES_BY_GROUP_UUID_REQUEST'
export const FETCH_ARTICLES_BY_GROUP_UUID_SUCCESS = 'FETCH_ARTICLES_BY_GROUP_UUID_SUCCESS'
export const FETCH_ARTICLES_BY_GROUP_UUID_FAILURE = 'FETCH_ARTICLES_BY_GROUP_UUID_FAILURE'

export const FETCH_FEATURE_ARTICLES_REQUEST = 'FETCH_FEATURE_ARTICLES_REQUEST'
export const FETCH_FEATURE_ARTICLES_SUCCESS = 'FETCH_FEATURE_ARTICLES_SUCCESS'
export const FETCH_FEATURE_ARTICLES_FAILURE = 'FETCH_FEATURE_ARTICLES_FAILURE'

export const SET_PROGRESS_PRECENTAGE = 'SET_PROGRESS_PRECENTAGE'
export const SET_PAGE_TYPE = 'SET_PAGE_TYPE'
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE'
export const SET_ARTICLE_TOPIC_LIST = 'SET_ARTICLE_TOPIC_LIST'
