const categoryPath = {
  world: 'world',
  humanrights: 'humanrights',
  politicsAndSociety: 'politics-and-society',
  health: 'health',
  environment: 'environment',
  econ: 'econ',
  culture: 'culture',
  education: 'education',
  podcast: 'podcast',
  opinion: 'opinion',
}

// todo: update id when db ready
export const CATEGORY = {
  [categoryPath.world]: { label: '國際兩岸', id: 'category-world' },
  [categoryPath.humanrights]: { label: '人權司法', id: 'category-humanrights' },
  [categoryPath.politicsAndSociety]: {
    label: '政治社會',
    id: 'category-politics-and-society',
  },
  [categoryPath.health]: { label: '醫療健康', id: 'category-health' },
  [categoryPath.environment]: { label: '環境永續', id: 'category-environmnet' },
  [categoryPath.econ]: { label: '經濟產業', id: 'category-econ' },
  [categoryPath.culture]: { label: '文化生活', id: 'category-culture' },
  [categoryPath.education]: { label: '教育校園', id: 'category-education' },
  [categoryPath.podcast]: { label: 'Podcast', id: 'category-podcast' },
  [categoryPath.opinion]: { label: '評論', id: 'category-opinion' },
}

// todo: update id when db ready
// subcategory: { path, id, label }
const subcategory = {
  all: { label: '全部', path: '' },
  hk: { label: '香港', path: 'hk' },
  china: { label: '中國', path: 'china' },
  us: { label: '美國', path: 'us' },
  jpAndKr: { label: '日韓', path: 'jp-and-kr' },
  southeastAsia: { label: '東南亞', path: 'southeast-asia' },
  europe: { label: '歐洲', path: 'europe' },
  others: { label: '其他', path: 'others' },
  gender: { label: '性別', path: 'gender' },
  labor: { label: '勞動', path: 'labor' },
  immigrant: { label: '移工與移民', path: 'immigrant' },
  housingJustice: { label: '居住正義', path: 'housing-justice' },
  transformationalJustice: {
    label: '轉型正義',
    path: 'transformational-justice',
  },
  mentalIllness: { label: '精神疾病', path: 'mental-illness' },
  justice: { label: '司法改革', path: 'justice' },
  digital: { label: '數位人權', path: 'digital' },
  election: { label: '選舉', path: 'election' },
  politicalPartyAndLocalFaction: {
    label: '政黨與地方政治',
    path: 'political-party-and-local-faction',
  },
  policy: { label: '政策', path: 'policy' },
  transportation: { label: '交通', path: 'transportation' },
  foodSafety: { label: '食安', path: 'food-safety' },
  informationWarfare: { label: '資訊戰', path: 'information-warfare' },
  socialwatch: { label: '社會觀察', path: 'socialwatch' },
  pandemic: { label: '疫情', path: 'pandemic' },
  healthPolicy: { label: '醫療政策', path: 'health-policy' },
  biotech: { label: '生物科技', path: 'biotech' },
  patientAutonomy: { label: '病人自主權利', path: 'patient-autonomy' },
  psychology: { label: '心理', path: 'psychology' },
  longTermCare: { label: '長照', path: 'long-term-care' },
  publicHealth: { label: '公共衛生', path: 'public-health' },
  energyEnv: { label: '能源', path: 'energy-env' },
  ocean: { label: '海洋', path: 'ocean' },
  mountainAndForest: { label: '山林', path: 'mountain-and-forest' },
  animal: { label: '動物', path: 'animal' },
  pollution: { label: '環境污染', path: 'pollution' },
  naturalDisaster: { label: '自然災害', path: 'natural-disaster' },
  economy: { label: '經濟', path: 'economy' },
  energyEcon: { label: '能源', path: 'energy-econ' },
  agriculture: { label: '農業', path: 'agriculture' },
  technology: { label: '科技', path: 'technology' },
  peAndSports: { label: '體育', path: 'pe-and-sports' },
  movie: { label: '電影', path: 'movie' },
  literature: { label: '文學', path: 'literature' },
  music: { label: '音樂', path: 'music' },
  dramaAndTheatre: { label: '戲劇', path: 'drama-and-theatre' },
  art: { label: '藝術', path: 'art' },
  eduPolicy: { label: '教育政策', path: 'edu-policy' },
  higherEducation: { label: '高等教育', path: 'higher-education' },
  teens: { label: '青少年', path: 'teens' },
  parenting: { label: '育兒', path: 'parenting' },
  lowBirthRate: { label: '少子化', path: 'low-birth-rate' },
  theRealStory: { label: 'The Real Story', path: 'the-real-story' },
  onTheGround: { label: 'On the Ground 路邊攤計畫', path: 'on-the-ground' },
  bookReview: { label: '書摘', path: 'book-review' },
  letter: { label: '讀者投書', path: 'letter' },
}

export const SUBCATEGORY = subcategory

export const CATEGORY_SET = {
  [categoryPath.world]: [
    subcategory.all,
    subcategory.hk,
    subcategory.china,
    subcategory.us,
    subcategory.jpAndKr,
    subcategory.southeastAsia,
    subcategory.europe,
    subcategory.others,
  ],
  [categoryPath.humanrights]: [
    subcategory.all,
    subcategory.gender,
    subcategory.labor,
    subcategory.immigrant,
    subcategory.housingJustice,
    subcategory.transformationalJustice,
    subcategory.mentalIllness,
    subcategory.justice,
    subcategory.digital,
  ],
  [categoryPath.politicsAndSociety]: [
    subcategory.all,
    subcategory.election,
    subcategory.politicalPartyAndLocalFaction,
    subcategory.policy,
    subcategory.transportation,
    subcategory.foodSafety,
    subcategory.informationWarfare,
    subcategory.socialwatch,
  ],
  [categoryPath.health]: [
    subcategory.all,
    subcategory.pandemic,
    subcategory.healthPolicy,
    subcategory.biotech,
    subcategory.patientAutonomy,
    subcategory.psychology,
    subcategory.longTermCare,
    subcategory.publicHealth,
  ],
  [categoryPath.environment]: [
    subcategory.all,
    subcategory.energyEnv,
    subcategory.ocean,
    subcategory.mountainAndForest,
    subcategory.animal,
    subcategory.pollution,
    subcategory.naturalDisaster,
  ],
  [categoryPath.econ]: [
    subcategory.all,
    subcategory.economy,
    subcategory.energyEcon,
    subcategory.agriculture,
    subcategory.technology,
  ],
  [categoryPath.culture]: [
    subcategory.all,
    subcategory.peAndSports,
    subcategory.movie,
    subcategory.literature,
    subcategory.music,
    subcategory.dramaAndTheatre,
    subcategory.art,
  ],
  [categoryPath.education]: [
    subcategory.all,
    subcategory.eduPolicy,
    subcategory.higherEducation,
    subcategory.teens,
    subcategory.parenting,
    subcategory.lowBirthRate,
  ],
  [categoryPath.podcast]: [
    subcategory.all,
    subcategory.theRealStory,
    subcategory.onTheGround,
  ],
  [categoryPath.opinion]: [
    subcategory.all,
    subcategory.bookReview,
    subcategory.letter,
  ],
}

export default {
  CATEGORY,
  SUBCATEGORY,
  CATEGORY_SET,
}
