'use strict'

const ARTICLE_STYLE = 'article'
const LONGFORM_ARTICLE_STYLE = 'longform'
const INTERACTIVE_ARTICLE_STYLE = 'interactive'
const PHOTOGRAPHY_ARTICLE_STYLE = 'photography'
const REVIEW_ARTICLE_STYLE = 'review'
const HOME = 'HOME'
const CATEGORY = 'CATEGORY'
const TAG = 'TAG'
const TOPIC = 'TOPIC'

export {
  ARTICLE_STYLE,
  CATEGORY,
  LONGFORM_ARTICLE_STYLE,
  INTERACTIVE_ARTICLE_STYLE,
  HOME,
  PHOTOGRAPHY_ARTICLE_STYLE,
  REVIEW_ARTICLE_STYLE,
  TAG,
  TOPIC
}
