'use strict'

const ARTICLE_STYLE = 'ARTICLE'
const LONGFORM_ARTICLE_STYLE = 'LONGFORM'
const INTERACTIVE_ARTICLE_STYLE = 'INTERACTIVE'
const PHOTOGRAPHY_ARTICLE_STYLE = 'PHOTOGRAPHY'
const REVIEW_ARTICLE_STYLE = 'REVIEW'
const HOME = 'HOME'
const CATEGORY = 'CATEGORY'
const TAG = 'TAG'
const TOPIC = 'TOPIC'

export {
  ARTICLE_STYLE,
  CATEGORY,
  LONGFORM_ARTICLE_STYLE,
  INTERACTIVE_ARTICLE_STYLE,
  HOME,
  PHOTOGRAPHY_ARTICLE_STYLE,
  REVIEW_ARTICLE_STYLE,
  TAG,
  TOPIC
}
