'use strict'
const CULTURE_CH_STR = '文化'
const INTL_CH_STR = '國際'
const HOME_CH_STR = '首頁'
const MEDIA_CH_STR = '媒體'
const REVIEW_CH_STR = '評論'
const SPECIAL_TOPIC_CH_STR = '專題'
const TAIWAN_CH_STR = '台灣'
const LOAD_MORE_AUTHORS_BTN = '載入更多作者'
const LOADING_MORE_AUTHORS = '載入更多作者'
const SEARCHING_AUTHOR_NAME = '搜尋作者'

export {
  CULTURE_CH_STR,
  INTL_CH_STR,
  HOME_CH_STR,
  MEDIA_CH_STR,
  REVIEW_CH_STR,
  SPECIAL_TOPIC_CH_STR,
  TAIWAN_CH_STR,
  LOAD_MORE_AUTHORS_BTN,
  LOADING_MORE_AUTHORS,
  SEARCHING_AUTHOR_NAME
}
