
export const membersImg = {
  digiChenNaLin: 'Digi-ChenNaLin.png',
  digiChingYangTseng: 'Digi-ChingYangTseng.png',
  digiMimiChen: 'Digi-MimiChen.png',
  digiNickLi: 'Digi-NickLi.png',
  digiTalorFang: 'Digi-TalorFang.png',
  digiYuChenHuang: 'Digi-YuChenHuang.png',
  digiYuChungJen: 'Digi-YuChungJen.png',
  digiDaDaWu: 'Digi-DadaWu.png',
  editBoWeiWu: 'Edit-BoWeiWu.png',
  editItingChiang: 'Edit-ItingChiang.png',
  editJenniferCheng: 'Edit-JenniferCheng.png',
  editJillYang: 'Edit-JillYang.png',
  editJungShinHo: 'Edit-JungShinHo.png',
  editKungTeLien: 'Edit-KungTeLien.png',
  editMichelleFang: 'Edit-MichelleFang.png',
  editSherryLee: 'Edit-SherryLee.png',
  editShihYunChang: 'Edit-ShihYunChang.png',
  editSylvieWang: 'Edit-SylvieWang.png',
  editSzuHuaChen: 'Edit-SzuHuaChen.png',
  editTzewuChang: 'Edit-TzewuChang.png',
  editUyo: 'Edit-Uyo.png',
  editWenTingYen: 'Edit-WenTing.png',
  editFuNienTsao: 'Edit-FuNienTsao.png',
  editJasonLiu: 'Edit-JasonLiu.png',
  editChhung:'Edit-chhung.png',
  editLinHuiChen: 'Edit-LinHuiChen.png',
  editSharonWang: 'Edit-SharonWang.png',
  photoChihWeiYu: 'Photo-ChihWeiYu.png',
  photoJamesonWu: 'Photo-JamesonWu.png',
  photoWeiMinSu: 'Photo-WeiMingSu.png',
  blankFace: 'blankface.png'
}

export const foundationImg = {
  foundationRongTsunHuang: 'foundation-RongTsunHuang.png',
  foundationSheuChiWong: 'foundation-SheuChiWong.png',
  foundationShiaoWeiChu: 'foundation-ShiaoWeiChu.png',
  foundationShuTienHuang: 'foundation-ShuTienHuang.png',
  foundationSoonShiaoChen: 'foundation-SoonShiaoChen.png',
  foundationWeiWanLi: 'foundation-WeiWanLi.png',
  foundationYiHanLin: 'foundation-YiHanLin.png',
  foundationYiRuLiu: 'foundation-YiRuLiu.png',
  foundationYiZhiLi: 'foundation-YiZhiLi.png',
  foundationWenYongHo: 'foundation-WenYongHo.png',
  foundationPoRuKo: 'foundation-PoRuKo.png',
  foundationZhiChang: 'foundation-ZhiChang.png',
  foundationChuShengHsu: 'foundation-ChuShengHsu.png',
  foundationChangDerLiu: 'foundation-ChangDerLiu.png',
  foundationYuChingTsai: 'foundation-YuChingTsai.png',
  foundationJaneLi: 'foundation-JaneLi.png',
  blankFace: 'blankface.png',
  editJungShinHo: membersImg.editJungShinHo,
  editSherryLee: membersImg.editSherryLee,
  editJenniferCheng: membersImg.editJenniferCheng,
  editSylvieWang: membersImg.editSylvieWang,
  editUyo: membersImg.editUyo
}
