
export const membersImg = {
  DigiChenNaLin: 'Digi-ChenNaLin.png',
  DigiChingYangTseng: 'Digi-ChingYangTseng.png',
  DigiMimiChen: 'Digi-MimiChen.png',
  DigiNickLi: 'Digi-NickLi.png',
  DigiTalorFang: 'Digi-TalorFang.png',
  DigiYuChenHuang: 'Digi-YuChenHuang.png',
  DigiYuChungJen: 'Digi-YuChungJen.png',
  DigiChenDaLin: 'Digi-ChenNaLin.png',
  EditBoWeiWu: 'Edit-BoWeiWu.png',
  EditItingChiang: 'Edit-ItingChiang.png',
  EditJenniferCheng: 'Edit-JenniferCheng.png',
  EditJillYang: 'Edit-JillYang.png',
  EditJungShinHo: 'Edit-JungShinHo.png',
  EditKungTeLien: 'Edit-KungTeLien.png',
  EditMichelleFang: 'Edit-MichelleFang.png',
  EditNicoFang: 'Edit-NicoFang.png',
  EditRosaWang: 'Edit-RosaWang.png',
  EditSherryLee: 'Edit-SherryLee.png',
  EditShihYunChang: 'Edit-ShihYunChang.png',
  EditSylvieWang: 'Edit-SylvieWang.png',
  EditSzuHuaChen: 'Edit-SzuHuaChen.png',
  EditTzewuChang: 'Edit-TzewuChang.png',
  EditUyo: 'Edit-Uyo.png',
  EditWenTingYen: 'Edit-TzewuChang.png',
  EditFuNienTsao: 'Edit-TzewuChang.png',
  EditPiChi: 'Edit-TzewuChang.png',
  PhotoChihWeiYu: 'Photo-ChihWeiYu.png',
  PhotoJamesonWu: 'Photo-JamesonWu.png',
  PhotoWeiMinSu: 'Photo-YuEnLin.png',
  BlankFace: 'blankface.png'
}

export const foundationImg = {
  foundationRongTsunHuang: 'foundation-RongTsunHuang.png',
  foundationSheuChiWong: 'foundation-SheuChiWong.png',
  foundationShiaoWeiChu: 'foundation-ShiaoWeiChu.png',
  foundationShuTienHuang: 'foundation-ShuTienHuang.png',
  foundationSoonShiaoChen: 'foundation-SoonShiaoChen.png',
  foundationWeiWanLi: 'foundation-WeiWanLi.png',
  foundationYiHanLin: 'foundation-YiHanLin.png',
  foundationYiRuLiu: 'foundation-YiRuLiu.png',
  foundationYiZhiLi: 'foundation-YiZhiLi.png',
  foundationWenYongHo: 'foundation-WenYongHo.png',
  foundationPoRuKo: 'foundation-PoRuKo.png',
  foundationZhiChang: 'foundation-ZhiChang.png',
  foundationChuShengHsu: 'foundation-ChuShengHsu.png',
  foundationChangDerLiu: 'foundation-ChangDerLiu.png',
  foundationYuChingTsai: 'foundation-YuChingTsai.png',
  BlankFace: 'blankface.png',
  EditJungShinHo: membersImg.EditJungShinHo,
  EditSherryLee: membersImg.EditSherryLee,
  EditJenniferCheng: membersImg.EditJenniferCheng,
  EditSylvieWang: membersImg.EditSylvieWang,
  EditUyo: membersImg.EditUyo
}
